import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { browserFixture } from './browser-fixture.ts';
import { checkMobileLayout } from './browser-layout.ts';

const fixture = await browserFixture();
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? '/usr/bin/google-chrome', headless: true });
const errors: string[] = [];
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(fixture.server.urls[0]);
  await page.waitForFunction(() => document.querySelector('#connection')?.textContent === 'Live');
  assert.equal(new URL(page.url()).search, '');
  const frame = page.frameLocator('#surface-frame');
  await frame.getByText('3 passed', { exact: true }).waitFor();
  await page.locator('#prompt').fill('Draft survives data updates');
  await writeFile(join(fixture.root, 'results.json'), '{"passed":42}');
  await frame.getByText('42 passed', { exact: true }).waitFor();
  assert.equal(await page.locator('#prompt').inputValue(), 'Draft survives data updates');
  assert.equal(fixture.calls.length, 0, 'filesystem reactivity needs no inference');
  await frame.locator('#ask').click();
  await page.waitForFunction(() => document.querySelector('#messages')?.textContent?.includes('Investigate this report'));
  assert.equal(fixture.calls.at(-1)?.method, 'followUp');
  assert.equal(fixture.calls.at(-1)?.params.surfaceId, fixture.surface.id);
  fixture.server.publish({ type: 'surface_event', surfaceId: fixture.surface.id, event: 'test-update', data: { text: 'Updated without HTML regeneration' } });
  await frame.getByText('Updated without HTML regeneration').waitFor();

  await page.locator('#actions-open').click();
  assert.equal(await page.locator('#actions-select option').count(), 3);
  await page.locator('#actions-search').fill('no matching command');
  assert.equal(await page.locator('#actions-run').isDisabled(), true);
  await page.locator('#actions-search').fill('review');
  assert.equal(await page.locator('#actions-select').inputValue(), 'skill:review');
  await page.locator('#actions-search').fill('template');
  assert.equal(await page.locator('#actions-select').inputValue(), 'summarize');
  await page.locator('#actions-search').fill('/demo');
  await page.locator('#actions-args').fill('src/index.ts --detail');
  fixture.failNext();
  await page.locator('#actions-run').click();
  await page.getByText(/Command not sent/).waitFor();
  assert.equal(await page.locator('#actions-args').inputValue(), 'src/index.ts --detail');
  await page.locator('#actions-run').click();
  await page.waitForFunction(() => !document.querySelector<HTMLDialogElement>('#actions-dialog')?.open);
  assert.deepEqual(fixture.calls.at(-1), { method: 'command', params: { name: 'demo', args: 'src/index.ts --detail' } });
  assert.equal(await page.locator('#prompt').inputValue(), 'Draft survives data updates');
  await page.locator('#notice-dismiss').click();

  await page.locator('#file-input').setInputFiles({ name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('test upload') });
  await page.waitForFunction(() => document.querySelector('.attachment')?.getAttribute('data-status') === 'ready');
  await page.locator('#send').click();
  await page.waitForFunction(() => document.querySelector<HTMLTextAreaElement>('#prompt')?.value === '');
  assert.equal(fixture.calls.at(-1)?.method, 'steer', 'Pi starts a normal turn when idle; steer delivery handles a concurrent transition to busy');
  assert.equal(await page.locator('#send-mode').count(), 0);
  assert.equal((fixture.calls.at(-1)?.params.attachments as string[]).length, 1);
  assert.equal(await page.locator('.attachment').count(), 0);

  await page.locator('#prompt').fill('Keep this after failure'); fixture.failNext();
  await page.locator('#send').click();
  await page.getByText(/Message not sent/).waitFor();
  assert.equal(await page.locator('#prompt').inputValue(), 'Keep this after failure');
  await page.locator('#notice-dismiss').click();
  await page.locator('#controls-open').click();
  await page.locator('#rename-input').fill('Renamed in browser');
  await page.getByRole('button', { name: 'Rename', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#session-name')?.textContent === 'Renamed in browser');
  await page.locator('#thinking-select').selectOption('high');
  await page.waitForFunction(() => document.querySelector('#control-notice')?.textContent?.includes('Updated'));
  await page.locator('#controls-close').click();
  fixture.state.uiPrompt = { type: 'ui_prompt_start', kind: 'confirm', title: 'Allow write?' };
  fixture.server.publish(fixture.state.uiPrompt);
  await page.getByText('Waiting in terminal: Allow write?').waitFor();
  fixture.state.uiPrompt = null;
  fixture.server.publish({ type: 'ui_prompt_end' });
  await mkdir(resolve('artifacts'), { recursive: true });
  await page.screenshot({ path: resolve('artifacts/desktop.png') });

  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.locator('#activity-toggle').click();
  await page.getByRole('button', { name: 'Close conversation', exact: true }).last().waitFor();
  await page.locator('#activity-close').click();
  await page.locator('#actions-open').click();
  await page.locator('#actions-search').fill('');
  await page.screenshot({ path: resolve('artifacts/mobile-actions.png') });
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#actions-open').evaluate(el => el === document.activeElement), true);
  await page.screenshot({ path: resolve('artifacts/mobile.png') });
  fixture.state.session.idle = false;
  fixture.server.publish({ type: 'state_changed' });
  await page.locator('#abort').waitFor();
  await page.locator('#prompt').fill('Steer the working Pi');
  await page.locator('#send').click();
  await page.waitForFunction(() => document.querySelector<HTMLTextAreaElement>('#prompt')?.value === '');
  assert.equal(fixture.calls.at(-1)?.method, 'steer');
  assert.equal(fixture.calls.at(-1)?.params.text, 'Steer the working Pi');
  await page.setViewportSize({ width: 320, height: 640 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  const actionBox = await page.locator('#actions-open').boundingBox();
  const sendBox = await page.locator('#send').boundingBox();
  assert.ok(actionBox && sendBox && actionBox.x + actionBox.width <= sendBox.x && sendBox.x + sendBox.width <= 320);
  await page.locator('#actions-open').click();
  assert.equal(await page.locator('#actions-run').isDisabled(), true);
  fixture.state.session.idle = true;
  fixture.server.publish({ type: 'state_changed' });
  await page.waitForFunction(() => !document.querySelector<HTMLButtonElement>('#actions-run')?.disabled);
  await page.locator('#actions-controls').click();
  await page.locator('#controls-title').waitFor();
  await page.locator('#controls-close').click();
  await page.locator('#prompt').fill('Still here after disconnect');
  await checkMobileLayout(browser, fixture.server.urls[0]);
  await fixture.server.close('new');
  await page.getByText(/new Return to the Pi terminal/).waitFor();
  assert.equal(await page.locator('#prompt').inputValue(), 'Still here after disconnect');
  assert.equal(await page.locator('#send').isDisabled(), true);
  assert.deepEqual(errors, []);
  console.log('Browser integration passed: auth, live data, same-session bridge, event patches, uploads, drafts, controls, mobile, shutdown.');
} finally { await browser.close(); await fixture.close(); }
